const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  console.log("Seeding Sama Al-Khadraa Phone Store database...");

  // 1. Users
  const buyer = await prisma.user.upsert({
    where: { email: "buyer@store.com" },
    update: {},
    create: {
      id: "demo-buyer-id",
      email: "buyer@store.com",
      name: "حيدر الكرخي (زبون)",
      role: "BUYER",
      phone: "+9647701234567",
    },
  });

  const sellerUser = await prisma.user.upsert({
    where: { email: "seller@store.com" },
    update: {},
    create: {
      id: "demo-seller-user-id",
      email: "seller@store.com",
      name: "سما الخضراء - مبيعات الهواتف",
      role: "SELLER",
      phone: "+9647809876543",
    },
  });

  const admin = await prisma.user.upsert({
    where: { email: "admin@store.com" },
    update: {},
    create: {
      id: "demo-admin-id",
      email: "admin@store.com",
      name: "المدير العام - سما الخضراء للهواتف",
      role: "ADMIN",
      phone: "+9647700000000",
    },
  });

  // 2. Seller Profile
  const sellerProfile = await prisma.sellerProfile.upsert({
    where: { userId: sellerUser.id },
    update: { 
      storeName: "سما الخضراء للهواتف الذكية والصيانة",
      description: "متجر سما الخضراء للهواتف الذكية: أحدث الهواتف الأصلية بالضمان، بيع مباشر وبالأقساط الميسرة، ورشة صيانة فورية متخصصة، ملحقات أصلية وخدمات مالية.",
    },
    create: {
      id: "demo-seller-profile-id",
      userId: sellerUser.id,
      storeName: "سما الخضراء للهواتف الذكية والصيانة",
      description: "متجر سما الخضراء للهواتف الذكية: أحدث الهواتف الأصلية بالضمان، بيع مباشر وبالأقساط الميسرة، ورشة صيانة فورية متخصصة، ملحقات أصلية وخدمات مالية.",
      rating: 4.98,
      phone: "+9647809876543",
    },
  });

  // 3. Products tailored strictly for a premier Iraqi Phone Store in IQD
  const productsData = [
    // Phones (الهواتف الذكية)
    {
      id: "prod-1",
      name: "آيفون 16 برو ماكس iPhone 16 Pro Max 256GB تيتانيوم صحراوي",
      description: "الهاتف الأقوى من أبل لعام 2025/2026. معالج A18 Pro الجبار، زر التحكم في الكاميرا Camera Control، بطارية عملاقة، كاميرا بيرسكوب 5x، وضمان رسمي سما الخضراء لمدة سنة كاملة.",
      price: 1850000,
      originalPrice: 1950000,
      stock: 15,
      category: "phones",
      imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02560?w=800",
      rating: 5.0,
      reviewsCount: 312,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-2",
      name: "سامسونج جالاكسي إس 24 ألترا Samsung Galaxy S24 Ultra 256GB تيتانيوم رمادي",
      description: "وحش الذكاء الاصطناعي Galaxy AI. شاشة مسطحة 6.8 إنش بدقة QHD+ وتردد 120Hz، قلم S-Pen مدمج، كاميرا 200 ميجابكسل، ومعالج Snapdragon 8 Gen 3 for Galaxy مع ضمان الوكيل المعتمد.",
      price: 1620000,
      originalPrice: 1720000,
      stock: 12,
      category: "phones",
      imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800",
      rating: 4.95,
      reviewsCount: 220,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-3",
      name: "شاومي 14 ألترا Xiaomi 14 Ultra 512GB تصوير لايكا الاحترافي",
      description: "قمة هندسة التصوير بالتعاون مع Leica مع مستشعر رئيسي 1 إنش وفتحة عدسة متغيرة، معالج Snapdragon 8 Gen 3، شحن فائق 90W وبطارية 5000mAh.",
      price: 1350000,
      originalPrice: 1450000,
      stock: 8,
      category: "phones",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800",
      rating: 4.88,
      reviewsCount: 94,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-4",
      name: "سامسونج جالاكسي إيه 55 Samsung Galaxy A55 5G 256GB أزرق ثلجي",
      description: "أفضل قيمة في الفئة المتوسطة العليا: إطار ألمنيوم فخم وظهر زجاجي، شاشة Super AMOLED 120Hz، مقاومة الماء IP67، وبطارية 5000mAh تدوم ليومين كاملين.",
      price: 445000,
      originalPrice: 480000,
      stock: 25,
      category: "phones",
      imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800",
      rating: 4.85,
      reviewsCount: 165,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-5",
      name: "آيفون 16 العادي iPhone 16 128GB أزرق الترامارين الجذاب",
      description: "أحدث أجيال آيفون بزر الإجراءات الجديد وزر التحكم بالكاميرا، معالج A18 السريع، وكاميرا 48 ميجابكسل بتقريب بصري 2x مدمج.",
      price: 1220000,
      originalPrice: 1300000,
      stock: 18,
      category: "phones",
      imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800",
      rating: 4.9,
      reviewsCount: 110,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-6",
      name: "شاومي ريدمي نوت 13 برو بلس Redmi Note 13 Pro+ 5G 512GB",
      description: "شاشة منحنية 1.5K AMOLED وتردد 120Hz، كاميرا 200 ميجابكسل مع تثبيت OIS، وشاحن جبار 120W يشحن الهاتف في 19 دقيقة.",
      price: 495000,
      originalPrice: 540000,
      stock: 14,
      category: "phones",
      imageUrl: "https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800",
      rating: 4.82,
      reviewsCount: 78,
      sellerId: sellerProfile.id,
    },

    // Headphones (السماعات)
    {
      id: "prod-7",
      name: "سماعات أبل إيربودز برو 2 Apple AirPods Pro 2 بمنفذ USB-C",
      description: "إلغاء نشط للضوضاء بمقدار مضاعف، نمط الصوت التكيفي وشفافية الصوت المتقدمة، مقاومة الماء والغبار IP54، وعلبة شحن مزودة بمكبر صوت ومحدد موقع دقيق.",
      price: 320000,
      originalPrice: 350000,
      stock: 30,
      category: "headphones",
      imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800",
      rating: 4.95,
      reviewsCount: 240,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-8",
      name: "سماعات سامسونج جالاكسي بودز 3 برو Galaxy Buds 3 Pro الفضية",
      description: "تصميم ثوري مزود بشريط ضوئي Blade Lights الأنيق، صوت استوديو فائق 24-bit Hi-Fi، تحسين صوت المكالمات بالذكاء الاصطناعي وإلغاء ضوضاء تكيفي.",
      price: 260000,
      originalPrice: 290000,
      stock: 18,
      category: "headphones",
      imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
      rating: 4.87,
      reviewsCount: 115,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-9",
      name: "سماعات أنكر ساوندكور ليبرتي 4 إن سي Anker Soundcore Liberty 4 NC",
      description: "تقليل الضوضاء بنسبة تصل إلى 98.5%، ترميز LDAC لصوت فائق الدقة، بطارية عملاقة حتى 50 ساعة استماع، و6 ميكروفونات بتقنية الذكاء الاصطناعي.",
      price: 95000,
      originalPrice: 115000,
      stock: 35,
      category: "headphones",
      imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
      rating: 4.89,
      reviewsCount: 142,
      sellerId: sellerProfile.id,
    },

    // Chargers (الشواحن والمنصات)
    {
      id: "prod-10",
      name: "شاحن أنكر برايم 65W جاليوم نايترايد Anker Prime GaN فائق السرعة",
      description: "شاحن ذكي فائق القوة 65 واط بثلاثة منافذ (2 USB-C + 1 USB-A). يشحن الهاتف والتابلت واللابتوب بسرعة خيالية مع تقنية ActiveShield 2.0 لمراقبة الحرارة.",
      price: 65000,
      originalPrice: 75000,
      stock: 45,
      category: "chargers",
      imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800",
      rating: 4.92,
      reviewsCount: 198,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-11",
      name: "رأس شاحن أبل أصلي 20W باور أدابتر Apple USB-C Power Adapter",
      description: "الشاحن المعتمد والرسمي من شركة أبل لهواتف الآيفون مع باركود فحص الأصالة وكفالة استبدال فوري من سما الخضراء.",
      price: 35000,
      originalPrice: 42000,
      stock: 80,
      category: "chargers",
      imageUrl: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800",
      rating: 4.96,
      reviewsCount: 420,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-12",
      name: "شاحن سامسونج فائق السرعة 45W أصلي مع كابل 5A Type-C",
      description: "شاحن سامسونج Super Fast Charging 2.0 المخصص لهواتف S24 Ultra و S23 Ultra لشحن الهاتف بنسبة 70% في 30 دقيقة فقط مع كابل مجدول أصلي.",
      price: 42000,
      originalPrice: 50000,
      stock: 50,
      category: "chargers",
      imageUrl: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800",
      rating: 4.88,
      reviewsCount: 156,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-13",
      name: "شاحن باسيوس 100W جاليوم نايتراid GaN5 Pro بأربعة منافذ",
      description: "محطة شحن مكتبية متطورة بقدرة 100W مع 2 USB-C و 2 USB-A، تدعم تقنيات الشحن السريع PD 3.0 و QC 4.0 لشحن 4 أجهزة بنفس اللحظة.",
      price: 78000,
      originalPrice: 90000,
      stock: 22,
      category: "chargers",
      imageUrl: "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=800",
      rating: 4.85,
      reviewsCount: 84,
      sellerId: sellerProfile.id,
    },

    // Cables (الكوابل والوصلات)
    {
      id: "prod-14",
      name: "كابل أنكر باورلاين بلس 100W تايب سي قماش مصفح Anker PowerLine+ 1.8m",
      description: "مقاومة انحناء فائقة لأكثر من 30,000 ثنية، نسيج نايلون مزدوج مضفر فائق المتانة يدعم سرعات نقل بيانات 480Mbps وشحن حتى 100 واط.",
      price: 22000,
      originalPrice: 28000,
      stock: 65,
      category: "cables",
      imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800",
      rating: 4.93,
      reviewsCount: 178,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-15",
      name: "كابل أبل أصلي منسوج تايب سي Apple 60W USB-C Woven Cable (1m)",
      description: "الكابل الأصلي المعتمد من أبل بتصميم منسوج فاخر يدعم الشحن السريع ونقل البيانات لجميع أجهزة iPhone 15 و 16 وأجهزة الآيباد.",
      price: 28000,
      originalPrice: 35000,
      stock: 70,
      category: "cables",
      imageUrl: "https://images.unsplash.com/photo-1603539947787-8e65839fa708?w=800",
      rating: 4.9,
      reviewsCount: 215,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-16",
      name: "كابل باسيوس شحن سريع 240W تايب سي عالي التحمل Baseus Type-C 2m",
      description: "كابل خارق يدعم أحدث معايير الشحن PD 3.1 حتى 240 واط، رقاقة E-Marker ذكية لتنظيم الجهد، وحماية سيليكون ونايلون ضد القطع.",
      price: 18000,
      originalPrice: 24000,
      stock: 45,
      category: "cables",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800",
      rating: 4.86,
      reviewsCount: 92,
      sellerId: sellerProfile.id,
    },

    // Cases & Protection (الحماية والكفرات)
    {
      id: "prod-17",
      name: "كفر سبيجن ألترا هايبرد ماج سيف Spigen Ultra Hybrid MagFit للآيفون",
      description: "ظهر شفاف مقاوم للاصفرار مع حواف ماصة للصدمات بتقنية Air Cushion، ومغناطيس مدمج متوافق تماماً مع جميع ملحقات شواحن MagSafe.",
      price: 32000,
      originalPrice: 40000,
      stock: 40,
      category: "cases",
      imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800",
      rating: 4.95,
      reviewsCount: 160,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-18",
      name: "بكج حماية درع نانو متكامل 360° مع كفر ماج سيف شفاف فاخر",
      description: "حماية عسكرية شاملة: لاصق نانو 9D ضد الصدمات والخدش، كفر حماية مقاوم للاصفرار يدعم شحن MagSafe، وحماية عدسات الكاميرا من الألمنيوم والزجاج الياقوتي.",
      price: 25000,
      originalPrice: 35000,
      stock: 120,
      category: "cases",
      imageUrl: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800",
      rating: 4.89,
      reviewsCount: 290,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-19",
      name: "كفر سامسونج سيليكون كفر أصلي مع حلقة إمساك لجالاكسي S24 Ultra",
      description: "كفر سامسونج الأصلي فائق النعومة بملمس مخملي فاخر، مزود بحزام سيليكون خلفي أنيق لحمل الهاتف بيد واحدة بأمان تام.",
      price: 38000,
      originalPrice: 45000,
      stock: 25,
      category: "cases",
      imageUrl: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800",
      rating: 4.84,
      reviewsCount: 68,
      sellerId: sellerProfile.id,
    },

    // Powerbanks (البطاريات والباوربانك)
    {
      id: "prod-20",
      name: "باوربانك أنكر 737 باوركور 24,000mAh طاقة 140W بشاشة ذكية",
      description: "الباوربانك الأقوى في العالم! منفذين Type-C بقدرة 140W، شاشة ملونة تعرض سرعة الشحن ونسبة البطارية والحرارة في الوقت الفعلي.",
      price: 165000,
      originalPrice: 190000,
      stock: 15,
      category: "powerbanks",
      imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800",
      rating: 4.97,
      reviewsCount: 88,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-21",
      name: "باوربانك باسيوس ماج سيف اللاسلكي 10,000mAh شحن سريع 20W",
      description: "تصميم نحيف وخفيف يلتصق خلف الآيفون بقوة مغناطيسية، شحن لاسلكي 15W وسلكي 20W، شاشة رقمية LED لنسبة الشحن.",
      price: 48000,
      originalPrice: 58000,
      stock: 35,
      category: "powerbanks",
      imageUrl: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800",
      rating: 4.88,
      reviewsCount: 112,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-22",
      name: "باوربانك أنكر 20,000mAh شحن سريع مزدوج 22.5W Power Bank",
      description: "سعة ضخمة تكفي لشحن هاتفك 4 إلى 5 مرات، منفذين Type-A ومنفذ Type-C، متانة عالية وتقنية PowerIQ لتوزيع الطاقة الذكي.",
      price: 52000,
      originalPrice: 62000,
      stock: 40,
      category: "powerbanks",
      imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800",
      rating: 4.91,
      reviewsCount: 175,
      sellerId: sellerProfile.id,
    },

    // Smartwatches (الساعات الذكية)
    {
      id: "prod-23",
      name: "ساعة أبل ووتش ألترا 2 Apple Watch Ultra 2 تيتانيوم 49 مم",
      description: "الساعة الرياضية الاحترافية الأقوى من أبل: هيكل تيتانيوم يتحمل أقسى الظروف، شاشة 3000 شمعة فائقة الوضوح، ونظام GPS ثنائي التردد.",
      price: 1120000,
      originalPrice: 1200000,
      stock: 7,
      category: "smartwatches",
      imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
      rating: 4.98,
      reviewsCount: 88,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-24",
      name: "ساعة سامسونج جالاكسي ووتش 7 الذكية Galaxy Watch 7 44mm",
      description: "أحدث معالج 3 نانومتر، حساس BioActive المتطور لمراقبة النوم ونبضات القلب والضغط، ودعم الذكاء الاصطناعي Galaxy AI في الردود.",
      price: 360000,
      originalPrice: 400000,
      stock: 16,
      category: "smartwatches",
      imageUrl: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800",
      rating: 4.89,
      reviewsCount: 65,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-25",
      name: "ساعة شاومي ووتش إس 3 الذكية Xiaomi Watch S3 بإطار قابل للتغيير",
      description: "شاشة AMOLED 1.43 إنش، بطارية خارقة تدوم حتى 15 يوماً، نظام HyperOS السريع، وتخصيص كامل للإطارات والأساور الرياضية.",
      price: 185000,
      originalPrice: 210000,
      stock: 20,
      category: "smartwatches",
      imageUrl: "https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800",
      rating: 4.82,
      reviewsCount: 44,
      sellerId: sellerProfile.id,
    },

    // Accessories (إكسسوارات عامة)
    {
      id: "prod-26",
      name: "قاعدة شحن لاسلكية أنكر ماج سيف 3 في 1 قابلة للطي للمكتب والسفر",
      description: "تشحن الآيفون وساعة أبل وسماعات إيربودز في آن واحد بقوة شحن سريع 15W مع دعم زاوية ستاند مريحة لمكالمات الفيديو.",
      price: 110000,
      originalPrice: 130000,
      stock: 20,
      category: "accessories",
      imageUrl: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=800",
      rating: 4.93,
      reviewsCount: 76,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-27",
      name: "مسكة ومسند هاتف مغناطيسي ماج سيف معدني Baseus Ring Holder",
      description: "مغناطيس روبيديوم خارق بقوة جذب 12N، دوران 360 درجة، ملمس ألمنيوم طيراني فخم متوافق مع كافة السيارات والستاندات.",
      price: 16000,
      originalPrice: 22000,
      stock: 55,
      category: "accessories",
      imageUrl: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800",
      rating: 4.85,
      reviewsCount: 130,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-28",
      name: "محول ذكي أنكر USB-C متعدد المنافذ 8 في 1 مع HDMI 4K و LAN",
      description: "توسيع فوري لأجهزة الآيباد واللابتوبات والهواتف الذكية مع دعم شحن توصيل الطاقة PD 100W وسرعة نقل بيانات فائقة.",
      price: 68000,
      originalPrice: 80000,
      stock: 18,
      category: "accessories",
      imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800",
      rating: 4.9,
      reviewsCount: 54,
      sellerId: sellerProfile.id,
    },

    // Maintenance (خدمات وقطع الصيانة المعتمدة)
    {
      id: "prod-29",
      name: "تبديل شاشة آيفون سوبر ريتينا OLED أصلية مع نقل نغمة True Tone",
      description: "استبدال شاشة مكسورة بشاشة أصلية وكالة مع نقل برمجة الحساس ونغمة ترو تون ومعايرة اللمس، وضمان ورشة سما الخضراء لمدة 6 أشهر.",
      price: 180000,
      originalPrice: 220000,
      stock: 10,
      category: "maintenance",
      imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800",
      rating: 4.98,
      reviewsCount: 210,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-30",
      name: "تبديل بطارية أبل / سامسونج أصلية وكالة مع ضمان سنة كاملة",
      description: "استعادة صحة البطارية إلى 100% بدون ظهور أي رسالة تحذيرية في الإعدادات، مع فحص دورة الشحن والحرارة وضمان استبدال فوري لمدة 365 يوماً.",
      price: 65000,
      originalPrice: 80000,
      stock: 15,
      category: "maintenance",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800",
      rating: 4.94,
      reviewsCount: 168,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-31",
      name: "فحص وإصلاح آي سي الشحن والباور (IC Power & Charging) بالمجهر الدقيق",
      description: "إصلاح الهواتف الفاصلة باور أو التي تفرغ الشحن سريعاً باستخدام أحدث مجاهر اللحام والمخططات الهندسية الأصلية في ورشة سما الخضراء.",
      price: 85000,
      originalPrice: 110000,
      stock: 20,
      category: "maintenance",
      imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02560?w=800",
      rating: 4.91,
      reviewsCount: 84,
      sellerId: sellerProfile.id,
    },

    // Deals (عروض وتخفيضات كبرى)
    {
      id: "prod-32",
      name: "بكج سما الخضراء الذهبي: شاحن 65W GaN + كابل مجدول + كفر ماج سيف + حماية شاشة",
      description: "وفر 35% مع البكج الشامل من سما الخضراء! يحتوي على رأس شحن 65W فائق السرعة، كابل 100W مصفح، كفر مقاوم للصدمات، ولصقة نانو 9D.",
      price: 89000,
      originalPrice: 140000,
      stock: 50,
      category: "deals",
      imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800",
      rating: 5.0,
      reviewsCount: 380,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-33",
      name: "آيفون 15 برو ماكس 256GB تيتانيوم أزرق (مستعمل فحص وكالة A+)",
      description: "جهاز مستعمل بحالة الوكالة شبه الجديد تماماً. فحص تقني 30 نقطة، نسبة البطارية 96%، لم يسبق صيانته، مع ضمان سما الخضراء المعتمد لمدة 6 أشهر.",
      price: 1380000,
      originalPrice: 1550000,
      stock: 4,
      category: "deals",
      imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800",
      rating: 4.95,
      reviewsCount: 52,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-34",
      name: "سامسونج جالاكسي إس 23 ألترا 256GB أسود فانتوم (مستعمل فحص وكالة A+)",
      description: "نظافة 100% مع كامل ملحقاته وكرتونته الأصلية. شاشة كاميرا وقلم أصلي بالكامل، بطارية 94%، خاضع لفحص مهندسي سما الخضراء مع ضمان استرجاع 14 يوم.",
      price: 990000,
      originalPrice: 1150000,
      stock: 3,
      category: "deals",
      imageUrl: "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=800",
      rating: 4.91,
      reviewsCount: 44,
      sellerId: sellerProfile.id,
    },

    // Gaming (ألعاب)
    {
      id: "prod-35",
      name: "يد تحكم بلايستيشن 5 دوال سينس لاسلكية Sony PS5 DualSense Wireless Controller",
      description: "ردود فعل لمسية غامرة، ومحفزات تكيفية ديناميكية، وميكروفون مدمج بتصميم أبيض وأسود أنيق متوافق مع الموبايل والكمبيوتر وبلايستيشن.",
      price: 95000,
      originalPrice: 110000,
      stock: 20,
      category: "gaming",
      imageUrl: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800",
      rating: 4.96,
      reviewsCount: 145,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-36",
      name: "سماعة قيمنق محيطية هايبر إكس HyperX Cloud III صوت نقي 7.1",
      description: "راحة فائقة برغوة الذاكرة الحصرية، مكبرات صوت 53 ملم بزاوية مضبوطة، وميكروفون فائق النقاء مانع للضوضاء للألعاب والمكالمات.",
      price: 125000,
      originalPrice: 145000,
      stock: 14,
      category: "gaming",
      imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
      rating: 4.92,
      reviewsCount: 88,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-37",
      name: "مروحة تبريد الهاتف المغناطيسية Black Shark MagCooler RGB",
      description: "تبريد شبه موصل خارق يخفض حرارة الهاتف حتى 15 درجة مئوية في ثوانٍ أثناء لعب ببجي وكول أوف ديوتي، مع إضاءة RGB مذهلة.",
      price: 38000,
      originalPrice: 48000,
      stock: 30,
      category: "gaming",
      imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800",
      rating: 4.88,
      reviewsCount: 120,
      sellerId: sellerProfile.id,
    },

    // Home (المنزل)
    {
      id: "prod-38",
      name: "شريط إضاءة ذكي فيليبس هيو Philips Hue Smart LED Gradient Lightstrip",
      description: "إضاءة تفاعلية متزامنة مع الموسيقى والشاشات تدعم 16 مليون لون، تحكم كامل بالصوت وتطبيق الهاتف مع Wi-Fi و Zigbee.",
      price: 115000,
      originalPrice: 135000,
      stock: 18,
      category: "home",
      imageUrl: "https://images.unsplash.com/photo-1550985543-f47f38aeee65?w=800",
      rating: 4.91,
      reviewsCount: 74,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-39",
      name: "كاميرا مراقبة منزلية ذكية Eufy Security 2K 360° مع ذكاء اصطناعي",
      description: "دقة 2K فائقة الوضوح، دوران 360 درجة أفقي و 96 درجة عمودي، تتبع تلقائي للحركة، رؤية ليلية بالأشعة تحت الحمراء وصوت ثنائي الاتجاه.",
      price: 68000,
      originalPrice: 82000,
      stock: 22,
      category: "home",
      imageUrl: "https://images.unsplash.com/photo-1557862921-37829c790f19?w=800",
      rating: 4.89,
      reviewsCount: 96,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-40",
      name: "توصيلة كهرباء ذكية متعددة المنافذ 30W Wi-Fi Smart Power Strip",
      description: "4 منافذ كهرباء مع 4 منافذ USB شحن سريع، تحكم منفصل لكل مقبس عبر التطبيق ومؤقت ذكي وحماية من ارتفاع الجهد.",
      price: 36000,
      originalPrice: 45000,
      stock: 40,
      category: "home",
      imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800",
      rating: 4.86,
      reviewsCount: 62,
      sellerId: sellerProfile.id,
    },

    // Bags (حقائب)
    {
      id: "prod-41",
      name: "حقيبة ظهر ذكية للابتوب Mark Ryden مضادة للسرقة والماء مع منفذ USB",
      description: "تصميم عصري هندسي صلب مضاد للصدمات، قفل رقمي TSA معتمد، وجيوب منظمة للابتوب والآيباد والأجهزة مع منفذ شحن خارجي مدمج.",
      price: 65000,
      originalPrice: 78000,
      stock: 25,
      category: "bags",
      imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800",
      rating: 4.93,
      reviewsCount: 110,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-42",
      name: "حقيبة كروس تقنية Tomtoc EDC خفيفة ومقاومة للخدش والماء",
      description: "حقيبة كتف مثالية لحمل الآيباد، المحفظة، الهاتف والشواحن، سحابات YKK اليابانية فائقة المتانة وحزام قابل للتعديل المريح.",
      price: 48000,
      originalPrice: 58000,
      stock: 30,
      category: "bags",
      imageUrl: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800",
      rating: 4.88,
      reviewsCount: 84,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-43",
      name: "محفظة كروت جلدية ماج سيف أبل Apple MagSafe Leather Wallet",
      description: "جلد أوروبي مدبوغ خصيصاً مع مغناطيس مدمج يلتصق بقوة خلف الآيفون مع دعم ميزة تحديد الموقع Find My ومساحة لـ 3 بطاقات.",
      price: 35000,
      originalPrice: 45000,
      stock: 45,
      category: "bags",
      imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800",
      rating: 4.91,
      reviewsCount: 130,
      sellerId: sellerProfile.id,
    },

    // Cars (سيارات)
    {
      id: "prod-44",
      name: "حامل وشاحن سيارة ماج سيف لاسلكي 15W Baseus MagPro لتكييف السيارة",
      description: "تثبيت مغناطيسي فائق القوة لا يتحرك على المطبات، شحن لاسلكي سريع 15W مع مروحة تبريد صامتة ومفصل كروي للدوران 360 درجة.",
      price: 42000,
      originalPrice: 52000,
      stock: 50,
      category: "cars",
      imageUrl: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800",
      rating: 4.94,
      reviewsCount: 165,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-45",
      name: "شاحن سيارة سوبر فاست 60W ميتال مزدوج Ugreen Dual Fast Car Charger",
      description: "هيكل ألمنيوم صلب بتصميم مدمج ومنفذين Type-C و USB-A يدعمان تقنيات الشحن السريع PD 30W و QC 30W مع إضاءة حلقة ناعمة.",
      price: 24000,
      originalPrice: 30000,
      stock: 60,
      category: "cars",
      imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800",
      rating: 4.9,
      reviewsCount: 198,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-46",
      name: "محول بلوتوث FM ومستقبل صوتي للسيارة Baseus Bluetooth 5.3 Car Transmitter",
      description: "اتصال بلوتوث نقي بدون تشويش، ميكروفون مدمج لإلغاء صدى المكالمات، شاشة رقمية لعرض الفولتية، ومنفذ فلاش ميموري USB.",
      price: 19000,
      originalPrice: 26000,
      stock: 40,
      category: "cars",
      imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800",
      rating: 4.87,
      reviewsCount: 140,
      sellerId: sellerProfile.id,
    },

    // Photography (تصوير)
    {
      id: "prod-47",
      name: "مانع اهتزاز جيمبل للموبايل DJI Osmo Mobile 6 الذكي للتصوير السينمائي",
      description: "تثبيت ثلاثي المحاور فائق النعومة، تتبع متقدم ActiveTrack 6.0، عصا تمديد مدمجة، وتشغيل فوري سريع عند فتح المشبك المغناطيسي.",
      price: 245000,
      originalPrice: 280000,
      stock: 10,
      category: "photography",
      imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800",
      rating: 4.98,
      reviewsCount: 78,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-48",
      name: "رينغ لايت 12 إنش ثلاثي الإضاءة مع حامل ترايبود مكتبي وأرضي متين",
      description: "إضاءة دائرية احترافية 3 درجات لون (أبيض، دافئ، طبيعي) مع 10 مستويات سطوع، حامل هاتف مرن وريموت تحكم بلوتوث عن بُعد.",
      price: 28000,
      originalPrice: 38000,
      stock: 55,
      category: "photography",
      imageUrl: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=800",
      rating: 4.85,
      reviewsCount: 160,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-49",
      name: "ميكروفون لاسلكي مزدوج للهواتف Boya BY-V20 Type-C لصناع المحتوى",
      description: "ميكروفونين مع مستقبل واحد للهاتف، صوت استوديو نقي وتقنية إلغاء الضوضاء الذكية بضغطة زر وبطارية تدوم 9 ساعات تسجيل.",
      price: 45000,
      originalPrice: 55000,
      stock: 35,
      category: "photography",
      imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
      rating: 4.91,
      reviewsCount: 92,
      sellerId: sellerProfile.id,
    },

    // Tablets (تابلت)
    {
      id: "prod-50",
      name: "آيباد إير iPad Air M2 128GB شاشة ريتينا 11 إنش باللون الرمادي الفلكي",
      description: "قوة شريحة Apple M2 الخارقة، شاشة Liquid Retina مضادة للانعكاس، كاميرا أمامية أفقية Center Stage، ودعم قلم Apple Pencil Pro.",
      price: 980000,
      originalPrice: 1050000,
      stock: 8,
      category: "tablets",
      imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800",
      rating: 4.97,
      reviewsCount: 64,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-51",
      name: "كيبورد ماجيك كيبورد مع لوحة تحكم تراك باد لجهاز iPad Air و Pro",
      description: "تصميم عائم فريد بمفصل مغناطيسي، مفاتيح بإضاءة خلفية مع آلية مقصية 1 مم لكتابة هادئة ومنفذ USB-C للشحن المتزامن.",
      price: 185000,
      originalPrice: 220000,
      stock: 15,
      category: "tablets",
      imageUrl: "https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?w=800",
      rating: 4.89,
      reviewsCount: 42,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-52",
      name: "قلم أبل الذكي Apple Pencil Pro مع حساسية الضغط والاهتزاز اللمسي",
      description: "إيماءة الضغط للتبديل بين الأدوات، تدوير البرميل للتحكم بالفرشاة، ردود فعل لمسية ودعم ميزة تحديد الموقع Find My.",
      price: 165000,
      originalPrice: 185000,
      stock: 20,
      category: "tablets",
      imageUrl: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800",
      rating: 4.95,
      reviewsCount: 88,
      sellerId: sellerProfile.id,
    },

    // Stands (ستاندات)
    {
      id: "prod-53",
      name: "ستاند مكتبي ألمنيوم Lamicall قابل للطي والدوران 360° للهاتف والتابلت",
      description: "هيكل معدني صلب ومزدوج المحاور يتحمل أثقل الهواتف والأجهزة اللوحية، مع وسائد سيليكون مانعة للانزلاق وفتحة تمرير كيبل الشحن.",
      price: 22000,
      originalPrice: 28000,
      stock: 60,
      category: "stands",
      imageUrl: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800",
      rating: 4.92,
      reviewsCount: 154,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-54",
      name: "حامل ماج سيف عائم للمكتب من الألمنيوم OMOTON MagSafe Stand",
      description: "زاوية رؤية مريحة لمكالمات FaceTime ووضع الاستعداد StandBy في iOS، مغناطيس ثابت وقاعدة ثقيلة متزنة على المكتب.",
      price: 26000,
      originalPrice: 34000,
      stock: 45,
      category: "stands",
      imageUrl: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800",
      rating: 4.88,
      reviewsCount: 76,
      sellerId: sellerProfile.id,
    },
    {
      id: "prod-55",
      name: "ستاند تابلت ولابتوب ألمنيوم بارتفاع وزوايا متعددة للتبريد المريح",
      description: "تصميم هندسي مفتوح يتيح تدفق الهواء لتبريد الأجهزة ومنع السخونة، قابل للطي بالكامل داخل الحقيبة مع 6 مستويات ارتفاع مريحة للرقبة.",
      price: 25000,
      originalPrice: 32000,
      stock: 50,
      category: "stands",
      imageUrl: "https://images.unsplash.com/photo-1526649661456-89c7ed4d00b8?w=800",
      rating: 4.9,
      reviewsCount: 115,
      sellerId: sellerProfile.id,
    },
  ];

  for (const p of productsData) {
    await prisma.product.upsert({
      where: { id: p.id },
      update: p,
      create: p,
    });
  }

  // 4. Sample Salary Disbursements (صرف الرواتب)
  await prisma.salaryDisbursement.deleteMany({});
  await prisma.salaryDisbursement.createMany({
    data: [
      {
        referenceNumber: "SAL-2026-1001",
        recipientName: "أحمد جاسم محمد",
        civilId: "198512345678",
        employeeNumber: "EMP-44821",
        department: "وزارة التربية - مديرية الكرخ",
        cardType: "ماستر كارد الرافدين",
        lastFourDigits: "8912",
        amount: 850000,
        fee: 3000,
        totalDisbursed: 847000,
        status: "Disbursed",
        notes: "صرف راتب شهر أيلول 2026",
      },
      {
        referenceNumber: "SAL-2026-1002",
        recipientName: "سعاد فاضل كاظم",
        civilId: "197298765432",
        employeeNumber: "RET-90123",
        department: "هيئة التقاعد الوطنية",
        cardType: "كي كارد (الرافدين)",
        lastFourDigits: "3341",
        amount: 620000,
        fee: 2000,
        totalDisbursed: 618000,
        status: "Disbursed",
        notes: "راتب تقاعدي مدني",
      },
      {
        referenceNumber: "SAL-2026-1003",
        recipientName: "علي خضير عباس",
        civilId: "199044556677",
        employeeNumber: "EMP-11982",
        department: "وزارة الصحة - دائرة صحة بغداد",
        cardType: "ماستر كارد الرشيد",
        lastFourDigits: "6720",
        amount: 1100000,
        fee: 3000,
        totalDisbursed: 1097000,
        status: "Disbursed",
        notes: "صرف يدوي من المنفذ",
      },
    ],
  });

  // 5. Sample Wallet Top-ups (زين كاش، كي كارد، نيو سويج، FIB)
  await prisma.walletTopup.deleteMany({});
  await prisma.walletTopup.createMany({
    data: [
      {
        referenceNumber: "WAL-ZAIN-8801",
        walletType: "ZAIN_CASH",
        serviceType: "DEPOSIT",
        customerPhone: "07801122334",
        amount: 250000,
        fee: 1000,
        totalCharge: 251000,
        status: "Success",
        operatorNotes: "إيداع رصيد محفظة زين كاش فوري",
      },
      {
        referenceNumber: "WAL-QI-4402",
        walletType: "QI_CARD",
        serviceType: "DEPOSIT",
        customerCard: "5324 •••• •••• 9901",
        amount: 500000,
        fee: 2000,
        totalCharge: 502000,
        status: "Success",
        operatorNotes: "تغذية بطاقة كي كارد",
      },
      {
        referenceNumber: "WAL-FIB-3301",
        walletType: "FIB",
        serviceType: "DEPOSIT",
        customerPhone: "07705544332",
        amount: 750000,
        fee: 1500,
        totalCharge: 751500,
        status: "Success",
        operatorNotes: "شحن حساب مصرف العراق الأول FIB",
      },
      {
        referenceNumber: "WAL-NEO-2201",
        walletType: "NEO_SWITCH",
        serviceType: "TRANSFER",
        customerCard: "9871 •••• •••• 4512",
        amount: 150000,
        fee: 1000,
        totalCharge: 151000,
        status: "Success",
        operatorNotes: "حوالة نيو سويج سريعة",
      },
    ],
  });

  // 6. Cash Vault Initial State (القاصة والتبادل)
  await prisma.vaultTransaction.deleteMany({});
  await prisma.vaultTransaction.createMany({
    data: [
      {
        type: "INCOME_CASH",
        currency: "IQD",
        amount: 25000000,
        description: "رصيد افتتاحي لقاصة الصندوق - دينار عراقي",
        balanceIQD: 25000000,
        balanceUSD: 12500,
      },
      {
        type: "INCOME_CASH",
        currency: "USD",
        amount: 12500,
        description: "رصيد افتتاحي لقاصة الصندوق - دولار أمريكي",
        balanceIQD: 25000000,
        balanceUSD: 12500,
      },
      {
        type: "EXCHANGE",
        currency: "USD",
        amount: 1000,
        exchangeRate: 1525,
        resultAmount: 1525000,
        description: "تصريف 1000 دولار إلى دينار بسعر 1525",
        balanceIQD: 26525000,
        balanceUSD: 11500,
      },
    ],
  });

  // 7. Maintenance Tickets (ورشة صيانة الهواتف الذكية)
  await prisma.maintenanceTicket.deleteMany({});
  await prisma.maintenanceTicket.createMany({
    data: [
      {
        ticketNumber: "MAINT-2026-101",
        customerName: "محمد مهدي علي",
        customerPhone: "07712349988",
        deviceType: "هاتف ذكي",
        brandModel: "iPhone 15 Pro Max",
        issueDescription: "كسر في الشاشة الخارجية وضعف أداء البطارية",
        accessories: "الجهاز فقط بدون كفر وبدون شاحن",
        estimatedCost: 195000,
        status: "In_Repair",
        technicianNotes: "تم تركيب شاشة OLED أصلية مع برمجة TrueTone، جاري فحص استقرار البطارية",
      },
      {
        ticketNumber: "MAINT-2026-102",
        customerName: "رنا سليم عبد",
        customerPhone: "07809988776",
        deviceType: "هاتف ذكي",
        brandModel: "Samsung Galaxy S24 Ultra",
        issueDescription: "عطل بمنفذ الشحن السريع Type-C وتجمع أتربة بمدخل قلم S-Pen",
        accessories: "الجهاز مع كفر الحماية الأصلي",
        estimatedCost: 55000,
        finalCost: 55000,
        status: "Ready",
        technicianNotes: "تم تنظيف وتبديل سوكيت الشحن الأصلي وفحص سحب التيار Super Fast Charging بنجاح",
      },
      {
        ticketNumber: "MAINT-2026-103",
        customerName: "حسام باسم",
        customerPhone: "07703344112",
        deviceType: "جهاز لوحي (تابلت)",
        brandModel: "iPad Pro 11 M2",
        issueDescription: "توقف الجهاز فجأة عن العمل ولا يقبل الشحن (عطل دائرة الباور)",
        accessories: "الآيباد فقط مع قلم Apple Pencil",
        estimatedCost: 120000,
        status: "Received",
        technicianNotes: "الجهاز على طاولة الفحص بانتظار فحص آيسي الباور PMIC",
      },
    ],
  });

  // 8. Installment Plans (البيع بالأقساط)
  await prisma.installmentPayment.deleteMany({});
  await prisma.installmentPlan.deleteMany({});

  const instPlan = await prisma.installmentPlan.create({
    data: {
      contractNumber: "INST-2026-501",
      customerName: "كرار حامد إبراهيم",
      customerPhone: "07812345678",
      nationalId: "200088776655",
      guarantorName: "عمار حامد إبراهيم (كفيل موظف)",
      guarantorPhone: "07709876543",
      productId: "prod-1",
      totalPrice: 1950000,
      downPayment: 350000,
      remainingAmount: 1600000,
      monthsCount: 10,
      monthlyInstallment: 160000,
      status: "Active",
      notes: "عقد تقسيط آيفون 16 برو ماكس على 10 أشهر - منفذ سما الخضراء",
      payments: {
        create: [
          {
            installmentNumber: 1,
            dueDate: new Date(2026, 8, 1),
            paidDate: new Date(2026, 8, 1),
            amount: 160000,
            status: "Paid",
            receiptNumber: "REC-INST-001",
          },
          {
            installmentNumber: 2,
            dueDate: new Date(2026, 9, 1),
            amount: 160000,
            status: "Pending",
          },
          {
            installmentNumber: 3,
            dueDate: new Date(2026, 10, 1),
            amount: 160000,
            status: "Pending",
          },
        ],
      },
    },
  });

  console.log("Sama Al-Khadraa Phone Store database seeded successfully with all departments!");
}

main()
  .catch((e) => {
    console.error("Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
